apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bpd7dc2zt-nodejs
  janus-idp.io/tekton: bpd7dc2zt-nodejs
  backstage.io/kubernetes-id: bpd7dc2zt-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bpd7dc2zt-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
