apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bpd7dc2zt-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bpd7dc2zt-nodejs 
  name: bpd7dc2zt-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: bpd7dc2zt-nodejs 
